service: pita

plugins:
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs10.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    UL_API_KEY: ${env:UL_API_KEY}
    AKASHI_API_KEY: ${env:AKASHI_API_KEY}

functions:
  app:
    handler: handler.app
    events:
      - http:
          method: post
          path: /slack/events
